Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `broadcast' for ChatRelay:Module      │····················